kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-gcp-proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-gcp-proxy/poao-gcp-proxy:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://poao-gcp-proxy.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
          cluster: dev-gcp
        - application: amt-arena-acl
          namespace: amt
          cluster: dev-gcp
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
  env:
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.pto.svc.nais.local/veilarboppfolging
    - name: NORG2_URL
      value: https://app-q1.adeo.no/norg2
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev.intern.nav.no/veilarbarena
    - name: AMT_ARENA_ORDS_PROXY_URL
      value: https://amt-arena-ords-proxy.dev.intern.nav.no
    - name: VEILARBAKTIVITET_URL
      value: http://veilarbaktivitet.pto.svc.nais.local/veilarbaktivitet

